{ inputs, ... }:
{
  imports = [
    inputs.home-manager.nixosModules.home-manager
    inputs.impermanence.nixosModules.impermanence
    inputs.sops-nix.nixosModules.sops
    ./adguardhome.nix
    ./avbroot.nix
    ./bpf-mark.nix
    ./chromium.nix
    ./clash.nix
    ./common.nix
    ./duckdns.nix
    ./fs.nix
    ./gammu-smsd.nix
    ./git.nix
    ./github-token.nix
    ./impermanence.nix
    ./metrics.nix
    ./nftables
    ./nginx.nix
    ./nogui.nix
    ./postgresql.nix
    ./refind
    ./restic.nix
    ./router.nix
    ./shadowsocks.nix
    ./sing-box.nix
    ./smartdns.nix
    ./ssh-agent.nix
    ./swanctl-dynamic-ipv6.nix
    ./swanctl-static.nix
    ./traefik.nix
    ./users.nix
    ./uu.nix
    ./uutunnel.nix
    ./vouch.nix
    ./warp.nix
    ./wireguard
    ./workstation.nix
  ];
}
