keys:
  - &admin_pgp F2E3DA8DE23F4EA11033EDEC535D184864C05736
  - &admin_age age1vtztgpzm0y0qqd4jjr37hmgfc6l6ptpyks5mgc5n0qk3zsmv9s8ssfw4xc
  - &rpi3 age1fl08lz0jhvmj468qs0c263dxsgdh0k95wdhz72wgc7rd6whgvu5s47uer0
creation_rules:
  - path_regex: machines/rpi3/.*
    key_groups:
    - pgp:
      - *admin_pgp
      age:
      - *admin_age
      - *rpi3
