# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  bullet = {
    pname = "bullet";
    version = "2.2.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/b/bullet/bullet-2.2.0.tar.gz";
      sha256 = "sha256-36D6gYEK0anmiIFcoE8kr4f/XNvoA7QvpjSx9Q/J2Ic=";
    };
  };
  efb-telegram-master = {
    pname = "efb-telegram-master";
    version = "v2.3.0";
    src = fetchFromGitHub {
      owner = "ehForwarderBot";
      repo = "efb-telegram-master";
      rev = "v2.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-pFetq8xnGyjd+EDl7G4OqtufPq3jCTxFpYqXm8WtFv4=";
    };
  };
  efb-wechat-slave = {
    pname = "efb-wechat-slave";
    version = "v2.0.7";
    src = fetchFromGitHub {
      owner = "ehForwarderBot";
      repo = "efb-wechat-slave";
      rev = "v2.0.7";
      fetchSubmodules = false;
      sha256 = "sha256-kDFajSfzXjESND0g+kJ/k5YpdjPzBLKYnpIv/6+eb54=";
    };
  };
  ehforwarderbot = {
    pname = "ehforwarderbot";
    version = "v2.1.1";
    src = fetchFromGitHub {
      owner = "ehForwarderBot";
      repo = "ehForwarderBot";
      rev = "v2.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-8axOxwb0NTjAFSFq84rZhYuNPZKakW3tUFDqy0i6jt0=";
    };
  };
  itchat = {
    pname = "itchat";
    version = "1.3.10";
    src = fetchurl {
      url = "https://pypi.org/packages/source/i/itchat/itchat-1.3.10.tar.gz";
      sha256 = "sha256-O7/xs3Vbx8qx+A5Wjai/RyDrRDAUPVUCJc43qNnQpMs=";
    };
  };
}
