# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  Fluent-solid-pink = {
    pname = "Fluent-solid-pink";
    version = "44794f29c89de994b0179aebabd2f5776c90d236";
    src = fetchFromGitHub {
      owner = "vinceliuice";
      repo = "Fluent-kde";
      rev = "44794f29c89de994b0179aebabd2f5776c90d236";
      fetchSubmodules = false;
      sha256 = "sha256-Ejr2wDs3tr36YN2mWSd9ZKp5e6gH/whcuhauN/2Y15I=";
    };
    date = "2025-11-10";
  };
  Nginx-Fancyindex-Theme = {
    pname = "Nginx-Fancyindex-Theme";
    version = "ee2e73c8dd1584b84ddad0cfcc44fbd903bdccd8";
    src = fetchFromGitHub {
      owner = "Naereen";
      repo = "Nginx-Fancyindex-Theme";
      rev = "ee2e73c8dd1584b84ddad0cfcc44fbd903bdccd8";
      fetchSubmodules = false;
      sha256 = "sha256-BrCnumxkMR2gmgwZVVXiQybjXSnpQwtrpQ0tH1AaWP0=";
    };
    date = "2026-01-30";
  };
  aleo = {
    pname = "aleo";
    version = "acd8d56d42be24d285708cf463652b194bdcddd2";
    src = fetchFromGitHub {
      owner = "AlessioLaiso";
      repo = "aleo";
      rev = "acd8d56d42be24d285708cf463652b194bdcddd2";
      fetchSubmodules = false;
      sha256 = "sha256-2CJTMJNTVCqjGAR24N82/cyhjOXg9HY/kCUZt4aILcE=";
    };
    date = "2025-08-08";
  };
  flood-for-transmission = {
    pname = "flood-for-transmission";
    version = "v1.0.1";
    src = fetchTarball {
      url = "https://github.com/johman10/flood-for-transmission/releases/download/v1.0.1/flood-for-transmission.tar.gz";
      sha256 = "sha256-DYqjF0axfJn0Mu7JJIhsB7xQ1uY2qLOIl4eZJsioOC8=";
    };
  };
  haier = {
    pname = "haier";
    version = "v1.2.0";
    src = fetchFromGitHub {
      owner = "banto6";
      repo = "haier";
      rev = "v1.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-92tla8+fvvym6cpz1ZQCjZZwx769diAN7GUzRM6DwGs=";
    };
  };
  kernelsu = {
    pname = "kernelsu";
    version = "v3.2.5";
    src = fetchFromGitHub {
      owner = "tiann";
      repo = "KernelSU";
      rev = "v3.2.5";
      fetchSubmodules = false;
      sha256 = "sha256-70I/UvKGcsR42yJfyD1jFeuY4XcDbCidUVPdqbNfIdE=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-70I_UvKGcsR42yJfyD1jFeuY4XcDbCidUVPdqbNfIdE=/Cargo.lock";
      outputHashes = {
        "kernlog-0.3.1" = "sha256-+jZvmmO4n3G2WWEfeMZpIPXbitM6svec8Q/4wtP8hhc=";
        "rustix-0.38.34" = "sha256-XzuiOKEvVee6nN8EltOgWrC4sUGhLKkm7pdPqDKuDWY=";
        "android-bootimg-0.1.0" = "sha256-b+W1/jpzccYP6QgsscjCm55bJXQjOTBR3BUB9u7j1wk=";
        "prop-rs-0.2.0" = "sha256-O3bSwrR2zmZGwOVxkZm/a9ETTi9MBjsGj1OJXAOtM9I=";
        "adb_client-3.1.1" = "sha256-+sfv/bvX6gIISV0vR88gCUpRrWL7OiShIxp0EEmE1T4=";
        "java-properties-2.0.0" = "sha256-fvekRqJI3Xwzo9z0Li36NFMIYnP5FMP8D9uVcK32soc=";
      };
    };
  };
  midea_auto_cloud = {
    pname = "midea_auto_cloud";
    version = "v0.4.5";
    src = fetchFromGitHub {
      owner = "sususweet";
      repo = "midea_auto_cloud";
      rev = "v0.4.5";
      fetchSubmodules = false;
      sha256 = "sha256-CGZmn/MhFIeq7c2JlyHOzjjYKv5KxVtqXM441NejttY=";
    };
  };
  owntracks-frontend = {
    pname = "owntracks-frontend";
    version = "v2.15.3";
    src = fetchTarball {
      url = "https://github.com/owntracks/frontend/releases/download/v2.15.3/v2.15.3-dist.zip";
      sha256 = "sha256-iy+yISPcOD/2lTyJUb1eI3wufLku1mKfVDm0+Dy8OKk=";
    };
  };
  transmission-client = {
    pname = "transmission-client";
    version = "a89c39bf8a5c8786becbd65d54e9f45f296a3b5a";
    src = fetchFromGitHub {
      owner = "zj9495";
      repo = "transmission-client";
      rev = "a89c39bf8a5c8786becbd65d54e9f45f296a3b5a";
      fetchSubmodules = false;
      sha256 = "sha256-paqfvc4NaT5fX7/P/HxA92C46WLqTaAegX9GiqaJK0s=";
    };
    date = "2023-02-15";
  };
  transmission-web-control = {
    pname = "transmission-web-control";
    version = "054e2edf7ee1ec859cec3ee5661a550481321a27";
    src = fetchFromGitHub {
      owner = "ronggang";
      repo = "transmission-web-control";
      rev = "054e2edf7ee1ec859cec3ee5661a550481321a27";
      fetchSubmodules = false;
      sha256 = "sha256-OsGT4emj6nLVNG87RZ/NW1RcSrw50phKGy04t45QvX8=";
    };
    date = "2025-06-01";
  };
  uuplugin-aarch64 = {
    pname = "uuplugin-aarch64";
    version = "14.0.6";
    src = fetchurl {
      url = "https://uurouter.gdl.netease.com/uuplugin/openwrt-aarch64/v14.0.6/uu.tar.gz";
      sha256 = "sha256-T+b8rVJcUlrVMK9p8QLZDBGJMw5OPDGDtXfd3idzHio=";
    };
  };
  uuplugin-x86_64 = {
    pname = "uuplugin-x86_64";
    version = "14.0.6";
    src = fetchurl {
      url = "https://uurouter.gdl.netease.com/uuplugin/openwrt-x86_64/v14.0.6/uu.tar.gz";
      sha256 = "sha256-G+zV74HSV7IgAvIIzTA7BOQhx9pCMVI7fYLaLHGTtX8=";
    };
  };
}
