name: "NixOS"
on:
  push:
  workflow_dispatch:
jobs:
  nixos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v11
      with:
        name: rvfg
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: nix-community
    - run: nix build .#nixosConfigurations.desktop.config.system.build.toplevel
    - run: nix build .#nixosConfigurations.xiaoxin.config.system.build.toplevel
    - run: nix build .#nixosConfigurations.work.config.system.build.toplevel
    - run: nix build .#nixosConfigurations.t430.config.system.build.toplevel
    - run: nix build .#nixosConfigurations.nl.config.system.build.toplevel
    - run: nix build .#nixosConfigurations.or2.config.system.build.toplevel
    - run: nix build .#nixosConfigurations.az.config.system.build.toplevel
    - run: nix build .#nixosConfigurations.nixctnr.config.system.build.toplevel
