name: "NixOS"
on:
  push:
  workflow_dispatch:
jobs:
  nixos:
    runs-on: ubuntu-latest
    steps:
    - name: Maximize build space
      uses: AdityaGarg8/remove-unwanted-software@v1
      with:
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
    - uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: rvfg
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: nix-community
    - run: nix build .#nixosConfigurations.desktop.config.system.build.toplevel
    - run: nix build .#nixosConfigurations.xiaoxin.config.system.build.toplevel
    - run: nix build .#nixosConfigurations.work.config.system.build.toplevel
    - run: nix build .#nixosConfigurations.t430.config.system.build.toplevel
    - run: nix build .#nixosConfigurations.nl.config.system.build.toplevel
    - run: nix build .#nixosConfigurations.or2.config.system.build.toplevel
    - run: nix build .#nixosConfigurations.az.config.system.build.toplevel
    - run: nix build .#nixosConfigurations.nixctnr.config.system.build.toplevel
